targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/app/domain/models/**/*
      freezed:
        generate_for:
          include:
            - lib/app/presentation/**/**_state.dart